// Auto-generated. Do not edit!

// (in-package industrial_extrinsic_cal.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class calibrationResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cost_per_observation = null;
    }
    else {
      if (initObj.hasOwnProperty('cost_per_observation')) {
        this.cost_per_observation = initObj.cost_per_observation
      }
      else {
        this.cost_per_observation = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type calibrationResult
    // Serialize message field [cost_per_observation]
    bufferOffset = _serializer.float64(obj.cost_per_observation, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type calibrationResult
    let len;
    let data = new calibrationResult(null);
    // Deserialize message field [cost_per_observation]
    data.cost_per_observation = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'industrial_extrinsic_cal/calibrationResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e0512b76935b097d08145b35b180a039';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    float64 cost_per_observation
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new calibrationResult(null);
    if (msg.cost_per_observation !== undefined) {
      resolved.cost_per_observation = msg.cost_per_observation;
    }
    else {
      resolved.cost_per_observation = 0.0
    }

    return resolved;
    }
};

module.exports = calibrationResult;
