(cl:defpackage camera_pose_calibration-srv
  (:use )
  (:export
   "CALIBRATECALL"
   "<CALIBRATECALL-REQUEST>"
   "CALIBRATECALL-REQUEST"
   "<CALIBRATECALL-RESPONSE>"
   "CALIBRATECALL-RESPONSE"
   "CALIBRATEFILE"
   "<CALIBRATEFILE-REQUEST>"
   "CALIBRATEFILE-REQUEST"
   "<CALIBRATEFILE-RESPONSE>"
   "CALIBRATEFILE-RESPONSE"
   "CALIBRATETOPIC"
   "<CALIBRATETOPIC-REQUEST>"
   "CALIBRATETOPIC-REQUEST"
   "<CALIBRATETOPIC-RESPONSE>"
   "CALIBRATETOPIC-RESPONSE"
  ))

