// Generated by gencpp from file robo_cylinder/MoveMetersRequest.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_MOVEMETERSREQUEST_H
#define ROBO_CYLINDER_MESSAGE_MOVEMETERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robo_cylinder
{
template <class ContainerAllocator>
struct MoveMetersRequest_
{
  typedef MoveMetersRequest_<ContainerAllocator> Type;

  MoveMetersRequest_()
    : meters(0.0)  {
    }
  MoveMetersRequest_(const ContainerAllocator& _alloc)
    : meters(0.0)  {
  (void)_alloc;
    }



   typedef float _meters_type;
  _meters_type meters;





  typedef boost::shared_ptr< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveMetersRequest_

typedef ::robo_cylinder::MoveMetersRequest_<std::allocator<void> > MoveMetersRequest;

typedef boost::shared_ptr< ::robo_cylinder::MoveMetersRequest > MoveMetersRequestPtr;
typedef boost::shared_ptr< ::robo_cylinder::MoveMetersRequest const> MoveMetersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robo_cylinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93e742ee24e961a724d1abfbc70257f7";
  }

  static const char* value(const ::robo_cylinder::MoveMetersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93e742ee24e961a7ULL;
  static const uint64_t static_value2 = 0x24d1abfbc70257f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_cylinder/MoveMetersRequest";
  }

  static const char* value(const ::robo_cylinder::MoveMetersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 meters\n\
";
  }

  static const char* value(const ::robo_cylinder::MoveMetersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.meters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveMetersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_cylinder::MoveMetersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_cylinder::MoveMetersRequest_<ContainerAllocator>& v)
  {
    s << indent << "meters: ";
    Printer<float>::stream(s, indent + "  ", v.meters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_MOVEMETERSREQUEST_H
