// Generated by gencpp from file robo_cylinder/MovePulsesRequest.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_MOVEPULSESREQUEST_H
#define ROBO_CYLINDER_MESSAGE_MOVEPULSESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robo_cylinder
{
template <class ContainerAllocator>
struct MovePulsesRequest_
{
  typedef MovePulsesRequest_<ContainerAllocator> Type;

  MovePulsesRequest_()
    : pulses(0)  {
    }
  MovePulsesRequest_(const ContainerAllocator& _alloc)
    : pulses(0)  {
  (void)_alloc;
    }



   typedef int32_t _pulses_type;
  _pulses_type pulses;





  typedef boost::shared_ptr< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MovePulsesRequest_

typedef ::robo_cylinder::MovePulsesRequest_<std::allocator<void> > MovePulsesRequest;

typedef boost::shared_ptr< ::robo_cylinder::MovePulsesRequest > MovePulsesRequestPtr;
typedef boost::shared_ptr< ::robo_cylinder::MovePulsesRequest const> MovePulsesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robo_cylinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5a6643c8e6676b12096d1cec7c1733d";
  }

  static const char* value(const ::robo_cylinder::MovePulsesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5a6643c8e6676b1ULL;
  static const uint64_t static_value2 = 0x2096d1cec7c1733dULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_cylinder/MovePulsesRequest";
  }

  static const char* value(const ::robo_cylinder::MovePulsesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pulses\n\
";
  }

  static const char* value(const ::robo_cylinder::MovePulsesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pulses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovePulsesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_cylinder::MovePulsesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_cylinder::MovePulsesRequest_<ContainerAllocator>& v)
  {
    s << indent << "pulses: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pulses);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_MOVEPULSESREQUEST_H
