// Generated by gencpp from file robo_cylinder/PowerIORequest.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_POWERIOREQUEST_H
#define ROBO_CYLINDER_MESSAGE_POWERIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robo_cylinder
{
template <class ContainerAllocator>
struct PowerIORequest_
{
  typedef PowerIORequest_<ContainerAllocator> Type;

  PowerIORequest_()
    : io(0)  {
    }
  PowerIORequest_(const ContainerAllocator& _alloc)
    : io(0)  {
  (void)_alloc;
    }



   typedef int16_t _io_type;
  _io_type io;





  typedef boost::shared_ptr< ::robo_cylinder::PowerIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_cylinder::PowerIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct PowerIORequest_

typedef ::robo_cylinder::PowerIORequest_<std::allocator<void> > PowerIORequest;

typedef boost::shared_ptr< ::robo_cylinder::PowerIORequest > PowerIORequestPtr;
typedef boost::shared_ptr< ::robo_cylinder::PowerIORequest const> PowerIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_cylinder::PowerIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robo_cylinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::PowerIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::PowerIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::PowerIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c58eb61491e897227b1da0d94435e381";
  }

  static const char* value(const ::robo_cylinder::PowerIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc58eb61491e89722ULL;
  static const uint64_t static_value2 = 0x7b1da0d94435e381ULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_cylinder/PowerIORequest";
  }

  static const char* value(const ::robo_cylinder::PowerIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 io\n\
";
  }

  static const char* value(const ::robo_cylinder::PowerIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.io);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_cylinder::PowerIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_cylinder::PowerIORequest_<ContainerAllocator>& v)
  {
    s << indent << "io: ";
    Printer<int16_t>::stream(s, indent + "  ", v.io);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_POWERIOREQUEST_H
