// Generated by gencpp from file robo_cylinder/StringCmd.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_STRINGCMD_H
#define ROBO_CYLINDER_MESSAGE_STRINGCMD_H

#include <ros/service_traits.h>


#include <robo_cylinder/StringCmdRequest.h>
#include <robo_cylinder/StringCmdResponse.h>


namespace robo_cylinder
{

struct StringCmd
{

typedef StringCmdRequest Request;
typedef StringCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringCmd
} // namespace robo_cylinder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo_cylinder::StringCmd > {
  static const char* value()
  {
    return "4d6784651d35dac8aad2a3eb7cbc01aa";
  }

  static const char* value(const ::robo_cylinder::StringCmd&) { return value(); }
};

template<>
struct DataType< ::robo_cylinder::StringCmd > {
  static const char* value()
  {
    return "robo_cylinder/StringCmd";
  }

  static const char* value(const ::robo_cylinder::StringCmd&) { return value(); }
};


// service_traits::MD5Sum< ::robo_cylinder::StringCmdRequest> should match 
// service_traits::MD5Sum< ::robo_cylinder::StringCmd > 
template<>
struct MD5Sum< ::robo_cylinder::StringCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo_cylinder::StringCmd >::value();
  }
  static const char* value(const ::robo_cylinder::StringCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_cylinder::StringCmdRequest> should match 
// service_traits::DataType< ::robo_cylinder::StringCmd > 
template<>
struct DataType< ::robo_cylinder::StringCmdRequest>
{
  static const char* value()
  {
    return DataType< ::robo_cylinder::StringCmd >::value();
  }
  static const char* value(const ::robo_cylinder::StringCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo_cylinder::StringCmdResponse> should match 
// service_traits::MD5Sum< ::robo_cylinder::StringCmd > 
template<>
struct MD5Sum< ::robo_cylinder::StringCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo_cylinder::StringCmd >::value();
  }
  static const char* value(const ::robo_cylinder::StringCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_cylinder::StringCmdResponse> should match 
// service_traits::DataType< ::robo_cylinder::StringCmd > 
template<>
struct DataType< ::robo_cylinder::StringCmdResponse>
{
  static const char* value()
  {
    return DataType< ::robo_cylinder::StringCmd >::value();
  }
  static const char* value(const ::robo_cylinder::StringCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_STRINGCMD_H
