// Generated by gencpp from file robo_cylinder/VelAccRequest.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_VELACCREQUEST_H
#define ROBO_CYLINDER_MESSAGE_VELACCREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robo_cylinder
{
template <class ContainerAllocator>
struct VelAccRequest_
{
  typedef VelAccRequest_<ContainerAllocator> Type;

  VelAccRequest_()
    : vel(0.0)
    , acc(0.0)  {
    }
  VelAccRequest_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , acc(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef float _acc_type;
  _acc_type acc;





  typedef boost::shared_ptr< ::robo_cylinder::VelAccRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_cylinder::VelAccRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelAccRequest_

typedef ::robo_cylinder::VelAccRequest_<std::allocator<void> > VelAccRequest;

typedef boost::shared_ptr< ::robo_cylinder::VelAccRequest > VelAccRequestPtr;
typedef boost::shared_ptr< ::robo_cylinder::VelAccRequest const> VelAccRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_cylinder::VelAccRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robo_cylinder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_cylinder::VelAccRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_cylinder::VelAccRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_cylinder::VelAccRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b0be12fb066cf8ae8d2477e777d23b4";
  }

  static const char* value(const ::robo_cylinder::VelAccRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b0be12fb066cf8aULL;
  static const uint64_t static_value2 = 0xe8d2477e777d23b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_cylinder/VelAccRequest";
  }

  static const char* value(const ::robo_cylinder::VelAccRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel\n\
float32 acc\n\
";
  }

  static const char* value(const ::robo_cylinder::VelAccRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.acc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelAccRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_cylinder::VelAccRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_cylinder::VelAccRequest_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "acc: ";
    Printer<float>::stream(s, indent + "  ", v.acc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_VELACCREQUEST_H
