(cl:defpackage target_finder-srv
  (:use )
  (:export
   "STEREO_LOCATOR"
   "<STEREO_LOCATOR-REQUEST>"
   "STEREO_LOCATOR-REQUEST"
   "<STEREO_LOCATOR-RESPONSE>"
   "STEREO_LOCATOR-RESPONSE"
   "TARGET_LOCATOR"
   "<TARGET_LOCATOR-REQUEST>"
   "TARGET_LOCATOR-REQUEST"
   "<TARGET_LOCATOR-RESPONSE>"
   "TARGET_LOCATOR-RESPONSE"
  ))

