// Generated by gencpp from file industrial_extrinsic_cal/cal_srv_solveResponse.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAL_SRV_SOLVERESPONSE_H
#define INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAL_SRV_SOLVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace industrial_extrinsic_cal
{
template <class ContainerAllocator>
struct cal_srv_solveResponse_
{
  typedef cal_srv_solveResponse_<ContainerAllocator> Type;

  cal_srv_solveResponse_()
    : final_cost_per_observation(0.0)
    , message()
    , success(false)  {
    }
  cal_srv_solveResponse_(const ContainerAllocator& _alloc)
    : final_cost_per_observation(0.0)
    , message(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef double _final_cost_per_observation_type;
  _final_cost_per_observation_type final_cost_per_observation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cal_srv_solveResponse_

typedef ::industrial_extrinsic_cal::cal_srv_solveResponse_<std::allocator<void> > cal_srv_solveResponse;

typedef boost::shared_ptr< ::industrial_extrinsic_cal::cal_srv_solveResponse > cal_srv_solveResponsePtr;
typedef boost::shared_ptr< ::industrial_extrinsic_cal::cal_srv_solveResponse const> cal_srv_solveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace industrial_extrinsic_cal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'industrial_extrinsic_cal': ['/home/sinchiguano/yumi_depends_ws/devel/share/industrial_extrinsic_cal/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f5bc25d120ef6b9096994fc430f1fee";
  }

  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f5bc25d120ef6b9ULL;
  static const uint64_t static_value2 = 0x096994fc430f1feeULL;
};

template<class ContainerAllocator>
struct DataType< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "industrial_extrinsic_cal/cal_srv_solveResponse";
  }

  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 final_cost_per_observation\n\
string message\n\
bool success\n\
";
  }

  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_cost_per_observation);
      stream.next(m.message);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cal_srv_solveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::industrial_extrinsic_cal::cal_srv_solveResponse_<ContainerAllocator>& v)
  {
    s << indent << "final_cost_per_observation: ";
    Printer<double>::stream(s, indent + "  ", v.final_cost_per_observation);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAL_SRV_SOLVERESPONSE_H
