// Generated by gencpp from file industrial_extrinsic_cal/cal_srv_solve.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAL_SRV_SOLVE_H
#define INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAL_SRV_SOLVE_H

#include <ros/service_traits.h>


#include <industrial_extrinsic_cal/cal_srv_solveRequest.h>
#include <industrial_extrinsic_cal/cal_srv_solveResponse.h>


namespace industrial_extrinsic_cal
{

struct cal_srv_solve
{

typedef cal_srv_solveRequest Request;
typedef cal_srv_solveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cal_srv_solve
} // namespace industrial_extrinsic_cal


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::industrial_extrinsic_cal::cal_srv_solve > {
  static const char* value()
  {
    return "ee44043b587910669da0ec6a74e20e6a";
  }

  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solve&) { return value(); }
};

template<>
struct DataType< ::industrial_extrinsic_cal::cal_srv_solve > {
  static const char* value()
  {
    return "industrial_extrinsic_cal/cal_srv_solve";
  }

  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solve&) { return value(); }
};


// service_traits::MD5Sum< ::industrial_extrinsic_cal::cal_srv_solveRequest> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::cal_srv_solve > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::cal_srv_solveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::cal_srv_solve >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::cal_srv_solveRequest> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::cal_srv_solve > 
template<>
struct DataType< ::industrial_extrinsic_cal::cal_srv_solveRequest>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::cal_srv_solve >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::industrial_extrinsic_cal::cal_srv_solveResponse> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::cal_srv_solve > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::cal_srv_solveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::cal_srv_solve >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::cal_srv_solveResponse> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::cal_srv_solve > 
template<>
struct DataType< ::industrial_extrinsic_cal::cal_srv_solveResponse>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::cal_srv_solve >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::cal_srv_solveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAL_SRV_SOLVE_H
