// Generated by gencpp from file industrial_extrinsic_cal/covariance.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_COVARIANCE_H
#define INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_COVARIANCE_H

#include <ros/service_traits.h>


#include <industrial_extrinsic_cal/covarianceRequest.h>
#include <industrial_extrinsic_cal/covarianceResponse.h>


namespace industrial_extrinsic_cal
{

struct covariance
{

typedef covarianceRequest Request;
typedef covarianceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct covariance
} // namespace industrial_extrinsic_cal


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::industrial_extrinsic_cal::covariance > {
  static const char* value()
  {
    return "007ea7659fcfafe13fcf466762341056";
  }

  static const char* value(const ::industrial_extrinsic_cal::covariance&) { return value(); }
};

template<>
struct DataType< ::industrial_extrinsic_cal::covariance > {
  static const char* value()
  {
    return "industrial_extrinsic_cal/covariance";
  }

  static const char* value(const ::industrial_extrinsic_cal::covariance&) { return value(); }
};


// service_traits::MD5Sum< ::industrial_extrinsic_cal::covarianceRequest> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::covariance > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::covarianceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::covariance >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::covarianceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::covarianceRequest> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::covariance > 
template<>
struct DataType< ::industrial_extrinsic_cal::covarianceRequest>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::covariance >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::covarianceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::industrial_extrinsic_cal::covarianceResponse> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::covariance > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::covarianceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::covariance >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::covarianceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::covarianceResponse> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::covariance > 
template<>
struct DataType< ::industrial_extrinsic_cal::covarianceResponse>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::covariance >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::covarianceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_COVARIANCE_H
