// Generated by gencpp from file industrial_extrinsic_cal/get_mutable_joint_statesResponse.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_GET_MUTABLE_JOINT_STATESRESPONSE_H
#define INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_GET_MUTABLE_JOINT_STATESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace industrial_extrinsic_cal
{
template <class ContainerAllocator>
struct get_mutable_joint_statesResponse_
{
  typedef get_mutable_joint_statesResponse_<ContainerAllocator> Type;

  get_mutable_joint_statesResponse_()
    : joint_names()
    , joint_values()  {
    }
  get_mutable_joint_statesResponse_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , joint_values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_values_type;
  _joint_values_type joint_values;





  typedef boost::shared_ptr< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_mutable_joint_statesResponse_

typedef ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<std::allocator<void> > get_mutable_joint_statesResponse;

typedef boost::shared_ptr< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse > get_mutable_joint_statesResponsePtr;
typedef boost::shared_ptr< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse const> get_mutable_joint_statesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace industrial_extrinsic_cal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'industrial_extrinsic_cal': ['/home/sinchiguano/yumi_depends_ws/devel/share/industrial_extrinsic_cal/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96580d86f44ff4fd7220e11741732cf0";
  }

  static const char* value(const ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96580d86f44ff4fdULL;
  static const uint64_t static_value2 = 0x7220e11741732cf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "industrial_extrinsic_cal/get_mutable_joint_statesResponse";
  }

  static const char* value(const ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] joint_names\n\
float64[] joint_values\n\
\n\
";
  }

  static const char* value(const ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.joint_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_mutable_joint_statesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::industrial_extrinsic_cal::get_mutable_joint_statesResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "joint_values[]" << std::endl;
    for (size_t i = 0; i < v.joint_values.size(); ++i)
    {
      s << indent << "  joint_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_GET_MUTABLE_JOINT_STATESRESPONSE_H
