// Generated by gencpp from file industrial_extrinsic_cal/user_accept.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_USER_ACCEPT_H
#define INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_USER_ACCEPT_H

#include <ros/service_traits.h>


#include <industrial_extrinsic_cal/user_acceptRequest.h>
#include <industrial_extrinsic_cal/user_acceptResponse.h>


namespace industrial_extrinsic_cal
{

struct user_accept
{

typedef user_acceptRequest Request;
typedef user_acceptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct user_accept
} // namespace industrial_extrinsic_cal


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::industrial_extrinsic_cal::user_accept > {
  static const char* value()
  {
    return "b67d6e018ba30c2c1c11d202c487d542";
  }

  static const char* value(const ::industrial_extrinsic_cal::user_accept&) { return value(); }
};

template<>
struct DataType< ::industrial_extrinsic_cal::user_accept > {
  static const char* value()
  {
    return "industrial_extrinsic_cal/user_accept";
  }

  static const char* value(const ::industrial_extrinsic_cal::user_accept&) { return value(); }
};


// service_traits::MD5Sum< ::industrial_extrinsic_cal::user_acceptRequest> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::user_accept > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::user_acceptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::user_accept >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::user_acceptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::user_acceptRequest> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::user_accept > 
template<>
struct DataType< ::industrial_extrinsic_cal::user_acceptRequest>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::user_accept >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::user_acceptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::industrial_extrinsic_cal::user_acceptResponse> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::user_accept > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::user_acceptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::user_accept >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::user_acceptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::user_acceptResponse> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::user_accept > 
template<>
struct DataType< ::industrial_extrinsic_cal::user_acceptResponse>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::user_accept >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::user_acceptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_USER_ACCEPT_H
