; Auto-generated. Do not edit!


(cl:in-package industrial_extrinsic_cal-msg)


;//! \htmlinclude calibrationGoal.msg.html

(cl:defclass <calibrationGoal> (roslisp-msg-protocol:ros-message)
  ((allowable_cost_per_observation
    :reader allowable_cost_per_observation
    :initarg :allowable_cost_per_observation
    :type cl:float
    :initform 0.0))
)

(cl:defclass calibrationGoal (<calibrationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <calibrationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'calibrationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name industrial_extrinsic_cal-msg:<calibrationGoal> is deprecated: use industrial_extrinsic_cal-msg:calibrationGoal instead.")))

(cl:ensure-generic-function 'allowable_cost_per_observation-val :lambda-list '(m))
(cl:defmethod allowable_cost_per_observation-val ((m <calibrationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader industrial_extrinsic_cal-msg:allowable_cost_per_observation-val is deprecated.  Use industrial_extrinsic_cal-msg:allowable_cost_per_observation instead.")
  (allowable_cost_per_observation m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <calibrationGoal>) ostream)
  "Serializes a message object of type '<calibrationGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'allowable_cost_per_observation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <calibrationGoal>) istream)
  "Deserializes a message object of type '<calibrationGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'allowable_cost_per_observation) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<calibrationGoal>)))
  "Returns string type for a message object of type '<calibrationGoal>"
  "industrial_extrinsic_cal/calibrationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'calibrationGoal)))
  "Returns string type for a message object of type 'calibrationGoal"
  "industrial_extrinsic_cal/calibrationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<calibrationGoal>)))
  "Returns md5sum for a message object of type '<calibrationGoal>"
  "018b5c6376abafbce2c3211a0d675d06")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'calibrationGoal)))
  "Returns md5sum for a message object of type 'calibrationGoal"
  "018b5c6376abafbce2c3211a0d675d06")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<calibrationGoal>)))
  "Returns full string definition for message of type '<calibrationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float64 allowable_cost_per_observation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'calibrationGoal)))
  "Returns full string definition for message of type 'calibrationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float64 allowable_cost_per_observation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <calibrationGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <calibrationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'calibrationGoal
    (cl:cons ':allowable_cost_per_observation (allowable_cost_per_observation msg))
))
