; Auto-generated. Do not edit!


(cl:in-package industrial_extrinsic_cal-msg)


;//! \htmlinclude manual_triggerFeedback.msg.html

(cl:defclass <manual_triggerFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass manual_triggerFeedback (<manual_triggerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <manual_triggerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'manual_triggerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name industrial_extrinsic_cal-msg:<manual_triggerFeedback> is deprecated: use industrial_extrinsic_cal-msg:manual_triggerFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <manual_triggerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader industrial_extrinsic_cal-msg:percent_complete-val is deprecated.  Use industrial_extrinsic_cal-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <manual_triggerFeedback>) ostream)
  "Serializes a message object of type '<manual_triggerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <manual_triggerFeedback>) istream)
  "Deserializes a message object of type '<manual_triggerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<manual_triggerFeedback>)))
  "Returns string type for a message object of type '<manual_triggerFeedback>"
  "industrial_extrinsic_cal/manual_triggerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'manual_triggerFeedback)))
  "Returns string type for a message object of type 'manual_triggerFeedback"
  "industrial_extrinsic_cal/manual_triggerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<manual_triggerFeedback>)))
  "Returns md5sum for a message object of type '<manual_triggerFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'manual_triggerFeedback)))
  "Returns md5sum for a message object of type 'manual_triggerFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<manual_triggerFeedback>)))
  "Returns full string definition for message of type '<manual_triggerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'manual_triggerFeedback)))
  "Returns full string definition for message of type 'manual_triggerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <manual_triggerFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <manual_triggerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'manual_triggerFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
