; Auto-generated. Do not edit!


(cl:in-package industrial_extrinsic_cal-msg)


;//! \htmlinclude robot_pose_triggerGoal.msg.html

(cl:defclass <robot_pose_triggerGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass robot_pose_triggerGoal (<robot_pose_triggerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_pose_triggerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_pose_triggerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name industrial_extrinsic_cal-msg:<robot_pose_triggerGoal> is deprecated: use industrial_extrinsic_cal-msg:robot_pose_triggerGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <robot_pose_triggerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader industrial_extrinsic_cal-msg:pose-val is deprecated.  Use industrial_extrinsic_cal-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_pose_triggerGoal>) ostream)
  "Serializes a message object of type '<robot_pose_triggerGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_pose_triggerGoal>) istream)
  "Deserializes a message object of type '<robot_pose_triggerGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_pose_triggerGoal>)))
  "Returns string type for a message object of type '<robot_pose_triggerGoal>"
  "industrial_extrinsic_cal/robot_pose_triggerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_pose_triggerGoal)))
  "Returns string type for a message object of type 'robot_pose_triggerGoal"
  "industrial_extrinsic_cal/robot_pose_triggerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_pose_triggerGoal>)))
  "Returns md5sum for a message object of type '<robot_pose_triggerGoal>"
  "f192399f711a48924df9a394d37edd67")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_pose_triggerGoal)))
  "Returns md5sum for a message object of type 'robot_pose_triggerGoal"
  "f192399f711a48924df9a394d37edd67")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_pose_triggerGoal>)))
  "Returns full string definition for message of type '<robot_pose_triggerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_pose_triggerGoal)))
  "Returns full string definition for message of type 'robot_pose_triggerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_pose_triggerGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_pose_triggerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_pose_triggerGoal
    (cl:cons ':pose (pose msg))
))
