// Generated by gencpp from file camera_pose_calibration/CalibrateCall.msg
// DO NOT EDIT!


#ifndef CAMERA_POSE_CALIBRATION_MESSAGE_CALIBRATECALL_H
#define CAMERA_POSE_CALIBRATION_MESSAGE_CALIBRATECALL_H

#include <ros/service_traits.h>


#include <camera_pose_calibration/CalibrateCallRequest.h>
#include <camera_pose_calibration/CalibrateCallResponse.h>


namespace camera_pose_calibration
{

struct CalibrateCall
{

typedef CalibrateCallRequest Request;
typedef CalibrateCallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibrateCall
} // namespace camera_pose_calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_pose_calibration::CalibrateCall > {
  static const char* value()
  {
    return "981c3ddc311ecd10123dd32e60417417";
  }

  static const char* value(const ::camera_pose_calibration::CalibrateCall&) { return value(); }
};

template<>
struct DataType< ::camera_pose_calibration::CalibrateCall > {
  static const char* value()
  {
    return "camera_pose_calibration/CalibrateCall";
  }

  static const char* value(const ::camera_pose_calibration::CalibrateCall&) { return value(); }
};


// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateCallRequest> should match 
// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateCall > 
template<>
struct MD5Sum< ::camera_pose_calibration::CalibrateCallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pose_calibration::CalibrateCall >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateCallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pose_calibration::CalibrateCallRequest> should match 
// service_traits::DataType< ::camera_pose_calibration::CalibrateCall > 
template<>
struct DataType< ::camera_pose_calibration::CalibrateCallRequest>
{
  static const char* value()
  {
    return DataType< ::camera_pose_calibration::CalibrateCall >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateCallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateCallResponse> should match 
// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateCall > 
template<>
struct MD5Sum< ::camera_pose_calibration::CalibrateCallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pose_calibration::CalibrateCall >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateCallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pose_calibration::CalibrateCallResponse> should match 
// service_traits::DataType< ::camera_pose_calibration::CalibrateCall > 
template<>
struct DataType< ::camera_pose_calibration::CalibrateCallResponse>
{
  static const char* value()
  {
    return DataType< ::camera_pose_calibration::CalibrateCall >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateCallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_POSE_CALIBRATION_MESSAGE_CALIBRATECALL_H
