// Generated by gencpp from file camera_pose_calibration/CalibrateTopic.msg
// DO NOT EDIT!


#ifndef CAMERA_POSE_CALIBRATION_MESSAGE_CALIBRATETOPIC_H
#define CAMERA_POSE_CALIBRATION_MESSAGE_CALIBRATETOPIC_H

#include <ros/service_traits.h>


#include <camera_pose_calibration/CalibrateTopicRequest.h>
#include <camera_pose_calibration/CalibrateTopicResponse.h>


namespace camera_pose_calibration
{

struct CalibrateTopic
{

typedef CalibrateTopicRequest Request;
typedef CalibrateTopicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibrateTopic
} // namespace camera_pose_calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_pose_calibration::CalibrateTopic > {
  static const char* value()
  {
    return "5e8812e45640426c831a0c069f6d5f72";
  }

  static const char* value(const ::camera_pose_calibration::CalibrateTopic&) { return value(); }
};

template<>
struct DataType< ::camera_pose_calibration::CalibrateTopic > {
  static const char* value()
  {
    return "camera_pose_calibration/CalibrateTopic";
  }

  static const char* value(const ::camera_pose_calibration::CalibrateTopic&) { return value(); }
};


// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateTopicRequest> should match 
// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateTopic > 
template<>
struct MD5Sum< ::camera_pose_calibration::CalibrateTopicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pose_calibration::CalibrateTopic >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateTopicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pose_calibration::CalibrateTopicRequest> should match 
// service_traits::DataType< ::camera_pose_calibration::CalibrateTopic > 
template<>
struct DataType< ::camera_pose_calibration::CalibrateTopicRequest>
{
  static const char* value()
  {
    return DataType< ::camera_pose_calibration::CalibrateTopic >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateTopicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateTopicResponse> should match 
// service_traits::MD5Sum< ::camera_pose_calibration::CalibrateTopic > 
template<>
struct MD5Sum< ::camera_pose_calibration::CalibrateTopicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_pose_calibration::CalibrateTopic >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateTopicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_pose_calibration::CalibrateTopicResponse> should match 
// service_traits::DataType< ::camera_pose_calibration::CalibrateTopic > 
template<>
struct DataType< ::camera_pose_calibration::CalibrateTopicResponse>
{
  static const char* value()
  {
    return DataType< ::camera_pose_calibration::CalibrateTopic >::value();
  }
  static const char* value(const ::camera_pose_calibration::CalibrateTopicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_POSE_CALIBRATION_MESSAGE_CALIBRATETOPIC_H
