(cl:in-package intrinsic_cal-srv)
(cl:export '(ALLOWABLE_COST_PER_OBSERVATION-VAL
          ALLOWABLE_COST_PER_OBSERVATION
          FINAL_COST_PER_OBSERVATION-VAL
          FINAL_COST_PER_OBSERVATION
          FINAL_POSE-VAL
          FINAL_POSE
))