(cl:in-package target_finder-srv)
(cl:export '(ALLOWABLE_COST_PER_OBSERVATION-VAL
          ALLOWABLE_COST_PER_OBSERVATION
          FINAL_COST_PER_OBSERVATION-VAL
          FINAL_COST_PER_OBSERVATION
          TARGET_POSE-VAL
          TARGET_POSE
))