// Generated by gencpp from file intrinsic_cal/rail_scal_runResponse.msg
// DO NOT EDIT!


#ifndef INTRINSIC_CAL_MESSAGE_RAIL_SCAL_RUNRESPONSE_H
#define INTRINSIC_CAL_MESSAGE_RAIL_SCAL_RUNRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace intrinsic_cal
{
template <class ContainerAllocator>
struct rail_scal_runResponse_
{
  typedef rail_scal_runResponse_<ContainerAllocator> Type;

  rail_scal_runResponse_()
    : final_cost_per_observation(0.0)
    , right_camera_pose()  {
    }
  rail_scal_runResponse_(const ContainerAllocator& _alloc)
    : final_cost_per_observation(0.0)
    , right_camera_pose(_alloc)  {
  (void)_alloc;
    }



   typedef double _final_cost_per_observation_type;
  _final_cost_per_observation_type final_cost_per_observation;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _right_camera_pose_type;
  _right_camera_pose_type right_camera_pose;





  typedef boost::shared_ptr< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rail_scal_runResponse_

typedef ::intrinsic_cal::rail_scal_runResponse_<std::allocator<void> > rail_scal_runResponse;

typedef boost::shared_ptr< ::intrinsic_cal::rail_scal_runResponse > rail_scal_runResponsePtr;
typedef boost::shared_ptr< ::intrinsic_cal::rail_scal_runResponse const> rail_scal_runResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace intrinsic_cal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "571691fb130bd61f46c5eb1d0995ca3e";
  }

  static const char* value(const ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x571691fb130bd61fULL;
  static const uint64_t static_value2 = 0x46c5eb1d0995ca3eULL;
};

template<class ContainerAllocator>
struct DataType< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intrinsic_cal/rail_scal_runResponse";
  }

  static const char* value(const ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 final_cost_per_observation\n\
geometry_msgs/Pose right_camera_pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_cost_per_observation);
      stream.next(m.right_camera_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rail_scal_runResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intrinsic_cal::rail_scal_runResponse_<ContainerAllocator>& v)
  {
    s << indent << "final_cost_per_observation: ";
    Printer<double>::stream(s, indent + "  ", v.final_cost_per_observation);
    s << indent << "right_camera_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.right_camera_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTRINSIC_CAL_MESSAGE_RAIL_SCAL_RUNRESPONSE_H
