(cl:in-package camera_pose_calibration-msg)
(cl:export '(PATTERN_WIDTH-VAL
          PATTERN_WIDTH
          PATTERN_HEIGHT-VAL
          PATTERN_HEIGHT
          PATTERN_DISTANCE-VAL
          PATTERN_DISTANCE
          NEIGHBOR_DISTANCE-VAL
          NEIGHBOR_DISTANCE
          VALID_PATTERN_RATIO_THRESHOLD-VAL
          VALID_PATTERN_RATIO_THRESHOLD
))