// Generated by gencpp from file industrial_extrinsic_cal/camera_observer_trigger.msg
// DO NOT EDIT!


#ifndef INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAMERA_OBSERVER_TRIGGER_H
#define INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAMERA_OBSERVER_TRIGGER_H

#include <ros/service_traits.h>


#include <industrial_extrinsic_cal/camera_observer_triggerRequest.h>
#include <industrial_extrinsic_cal/camera_observer_triggerResponse.h>


namespace industrial_extrinsic_cal
{

struct camera_observer_trigger
{

typedef camera_observer_triggerRequest Request;
typedef camera_observer_triggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct camera_observer_trigger
} // namespace industrial_extrinsic_cal


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::industrial_extrinsic_cal::camera_observer_trigger > {
  static const char* value()
  {
    return "47ad3ec1797cb1642f250ccac426d28b";
  }

  static const char* value(const ::industrial_extrinsic_cal::camera_observer_trigger&) { return value(); }
};

template<>
struct DataType< ::industrial_extrinsic_cal::camera_observer_trigger > {
  static const char* value()
  {
    return "industrial_extrinsic_cal/camera_observer_trigger";
  }

  static const char* value(const ::industrial_extrinsic_cal::camera_observer_trigger&) { return value(); }
};


// service_traits::MD5Sum< ::industrial_extrinsic_cal::camera_observer_triggerRequest> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::camera_observer_trigger > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::camera_observer_triggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::camera_observer_trigger >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::camera_observer_triggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::camera_observer_triggerRequest> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::camera_observer_trigger > 
template<>
struct DataType< ::industrial_extrinsic_cal::camera_observer_triggerRequest>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::camera_observer_trigger >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::camera_observer_triggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::industrial_extrinsic_cal::camera_observer_triggerResponse> should match 
// service_traits::MD5Sum< ::industrial_extrinsic_cal::camera_observer_trigger > 
template<>
struct MD5Sum< ::industrial_extrinsic_cal::camera_observer_triggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::industrial_extrinsic_cal::camera_observer_trigger >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::camera_observer_triggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::industrial_extrinsic_cal::camera_observer_triggerResponse> should match 
// service_traits::DataType< ::industrial_extrinsic_cal::camera_observer_trigger > 
template<>
struct DataType< ::industrial_extrinsic_cal::camera_observer_triggerResponse>
{
  static const char* value()
  {
    return DataType< ::industrial_extrinsic_cal::camera_observer_trigger >::value();
  }
  static const char* value(const ::industrial_extrinsic_cal::camera_observer_triggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INDUSTRIAL_EXTRINSIC_CAL_MESSAGE_CAMERA_OBSERVER_TRIGGER_H
