// Generated by gencpp from file robo_cylinder/PowerIO.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_POWERIO_H
#define ROBO_CYLINDER_MESSAGE_POWERIO_H

#include <ros/service_traits.h>


#include <robo_cylinder/PowerIORequest.h>
#include <robo_cylinder/PowerIOResponse.h>


namespace robo_cylinder
{

struct PowerIO
{

typedef PowerIORequest Request;
typedef PowerIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PowerIO
} // namespace robo_cylinder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo_cylinder::PowerIO > {
  static const char* value()
  {
    return "2f3ab81f85bd2b368501f94f9d2164e9";
  }

  static const char* value(const ::robo_cylinder::PowerIO&) { return value(); }
};

template<>
struct DataType< ::robo_cylinder::PowerIO > {
  static const char* value()
  {
    return "robo_cylinder/PowerIO";
  }

  static const char* value(const ::robo_cylinder::PowerIO&) { return value(); }
};


// service_traits::MD5Sum< ::robo_cylinder::PowerIORequest> should match 
// service_traits::MD5Sum< ::robo_cylinder::PowerIO > 
template<>
struct MD5Sum< ::robo_cylinder::PowerIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo_cylinder::PowerIO >::value();
  }
  static const char* value(const ::robo_cylinder::PowerIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_cylinder::PowerIORequest> should match 
// service_traits::DataType< ::robo_cylinder::PowerIO > 
template<>
struct DataType< ::robo_cylinder::PowerIORequest>
{
  static const char* value()
  {
    return DataType< ::robo_cylinder::PowerIO >::value();
  }
  static const char* value(const ::robo_cylinder::PowerIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo_cylinder::PowerIOResponse> should match 
// service_traits::MD5Sum< ::robo_cylinder::PowerIO > 
template<>
struct MD5Sum< ::robo_cylinder::PowerIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo_cylinder::PowerIO >::value();
  }
  static const char* value(const ::robo_cylinder::PowerIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_cylinder::PowerIOResponse> should match 
// service_traits::DataType< ::robo_cylinder::PowerIO > 
template<>
struct DataType< ::robo_cylinder::PowerIOResponse>
{
  static const char* value()
  {
    return DataType< ::robo_cylinder::PowerIO >::value();
  }
  static const char* value(const ::robo_cylinder::PowerIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_POWERIO_H
