// Generated by gencpp from file robo_cylinder/VelAcc.msg
// DO NOT EDIT!


#ifndef ROBO_CYLINDER_MESSAGE_VELACC_H
#define ROBO_CYLINDER_MESSAGE_VELACC_H

#include <ros/service_traits.h>


#include <robo_cylinder/VelAccRequest.h>
#include <robo_cylinder/VelAccResponse.h>


namespace robo_cylinder
{

struct VelAcc
{

typedef VelAccRequest Request;
typedef VelAccResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelAcc
} // namespace robo_cylinder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo_cylinder::VelAcc > {
  static const char* value()
  {
    return "f35bf9280520074b859fc92770147f86";
  }

  static const char* value(const ::robo_cylinder::VelAcc&) { return value(); }
};

template<>
struct DataType< ::robo_cylinder::VelAcc > {
  static const char* value()
  {
    return "robo_cylinder/VelAcc";
  }

  static const char* value(const ::robo_cylinder::VelAcc&) { return value(); }
};


// service_traits::MD5Sum< ::robo_cylinder::VelAccRequest> should match 
// service_traits::MD5Sum< ::robo_cylinder::VelAcc > 
template<>
struct MD5Sum< ::robo_cylinder::VelAccRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo_cylinder::VelAcc >::value();
  }
  static const char* value(const ::robo_cylinder::VelAccRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_cylinder::VelAccRequest> should match 
// service_traits::DataType< ::robo_cylinder::VelAcc > 
template<>
struct DataType< ::robo_cylinder::VelAccRequest>
{
  static const char* value()
  {
    return DataType< ::robo_cylinder::VelAcc >::value();
  }
  static const char* value(const ::robo_cylinder::VelAccRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo_cylinder::VelAccResponse> should match 
// service_traits::MD5Sum< ::robo_cylinder::VelAcc > 
template<>
struct MD5Sum< ::robo_cylinder::VelAccResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo_cylinder::VelAcc >::value();
  }
  static const char* value(const ::robo_cylinder::VelAccResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo_cylinder::VelAccResponse> should match 
// service_traits::DataType< ::robo_cylinder::VelAcc > 
template<>
struct DataType< ::robo_cylinder::VelAccResponse>
{
  static const char* value()
  {
    return DataType< ::robo_cylinder::VelAcc >::value();
  }
  static const char* value(const ::robo_cylinder::VelAccResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_CYLINDER_MESSAGE_VELACC_H
